# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Cloud Foundry (API Gateway)

on:
  push:
    branches:
      - main
env:
  NODE_VERSION: '12.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install NestJS
        run: npm install -g @nestjs/cli

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build API Gateway
        run: yarn build gateway

      - name: Build Libraries
        run: nest build common && nest build models  

      - name: Deploy      
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: https://api.cf.us10.hana.ondemand.com
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: dev
          command: push adrianodrix-smartranking-api-gateway  
      