# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Example: https://github.com/marketplace/actions/cf-cli-action
name: Deploy to Cloud Foundry (API Gateway)

env:
  NODE_VERSION: '10.x'                # set this to the node version to use

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build API Gateway
        run: yarn build gateway
      - name: Build Libraries
        run: nest build common && nest build models  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: citizen-of-planet-earth/cf-cli-action@master
      with:
        cf_api: https://api.cf.us10.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: ${{ secrets.CF_ORG }}
        cf_space: trial
        command: push adrianodrix-smartranking-api-gateway